language: cpp

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libjansson-dev libcurl4-openssl-dev sendemail

before_script:
  - cmake --version

script:
  - cmake -B./build -H.
  - cmake --build ./build -- install
